"""
MWS Invoice Parser — FastAPI application.

Routes (all mounted at root; Vite proxy strips /api prefix):
  POST /parse                           — upload PDF, parse, validate, return rows + page images
  POST /save                            — insert rows into Supabase; upload PDF to Storage
  GET  /records/{site}                  — fetch saved records (asc; optional date filters)
  PUT  /records/{site}/{id}             — update a single record
  DELETE /records/{site}/{id}           — delete a single record
  GET  /check-duplicate/{site}          — check for duplicate by invoice_number or fuzzy match
  GET  /sites/{site}                    — get site metadata
  PUT  /sites/{site}                    — update site metadata
  GET  /pdf/{site}/{id}                 — get signed PDF download URL
  GET  /export/{site}                   — download .xlsx tracker in Melissa's exact format
"""

from __future__ import annotations

import base64
import os
import tempfile
from io import BytesIO
from typing import Any, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel

load_dotenv()

app = FastAPI(
    title="MWS Invoice Parser API",
    description="Parses Enbridge CNG and Elexicon electricity PDF invoices for Miller Waste Systems.",
    version="0.3.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "https://mws-invoice-parser.vercel.app",
        "https://mws-invoice-parser-skormzys-projects.vercel.app",
    ],
    allow_origin_regex=r"https://mws-invoice-parser-.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─────────────────────────────────────────────────────────────
# Exception handlers
# ─────────────────────────────────────────────────────────────

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError) -> JSONResponse:
    """
    Safely serialize FastAPI validation errors without crashing on binary data
    (e.g. raw PDF bytes in request body misrouted to a JSON endpoint).
    """
    safe_errors = []
    for error in exc.errors():
        safe_error: dict[str, Any] = {}
        for k, v in error.items():
            if isinstance(v, bytes):
                safe_error[k] = f"<binary {len(v)} bytes>"
            elif isinstance(v, (list, tuple)):
                safe_error[k] = [f"<binary {len(i)} bytes>" if isinstance(i, bytes) else i for i in v]
            else:
                safe_error[k] = v
        safe_errors.append(safe_error)
    return JSONResponse(status_code=422, content={"detail": safe_errors})


# ─────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────

_TABLE_MAP = {
    "cambridge": "cambridge_invoices",
    "pickering_cng": "pickering_cng_invoices",
    "walgreen": "walgreen_invoices",
    "pickering_elexicon": "pickering_elexicon_invoices",
}

# Column used for ascending sort per site
_ORDER_COL = {
    "cambridge": "start_date",
    "pickering_cng": "start_date",
    "walgreen": "start_date",
    "pickering_elexicon": "created_at",
}

_SITE_NAMES = {
    "cambridge": "Cambridge_CNG",
    "pickering_cng": "Pickering_CNG",
    "walgreen": "Walgreen_CNG",
    "pickering_elexicon": "Pickering_Elexicon",
}

# Fields auto-generated by Supabase — strip before insert/update
_AUTO_FIELDS = {"id", "created_at"}

_STORAGE_BUCKET = "invoices"


# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────

def _get_supabase():
    url = os.environ.get("SUPABASE_URL", "")
    key = os.environ.get("SUPABASE_SERVICE_KEY", "")
    if not url or not key:
        raise HTTPException(
            status_code=503,
            detail="Supabase is not configured. Set SUPABASE_URL and SUPABASE_SERVICE_KEY.",
        )
    from supabase import create_client  # type: ignore[import]
    return create_client(url, key)


def _dispatch_parse(invoice_type: str, pdf_path: str, filename: str) -> tuple[list[Any], list[Any]]:
    if invoice_type == "cambridge":
        from parsers.cambridge import parse_cambridge
        return parse_cambridge(pdf_path, filename)
    elif invoice_type == "pickering_cng":
        from parsers.pickering_enbridge import parse_pickering_enbridge
        return parse_pickering_enbridge(pdf_path, filename)
    elif invoice_type == "walgreen":
        from parsers.walgreen import parse_walgreen
        return parse_walgreen(pdf_path, filename)
    elif invoice_type == "pickering_elexicon":
        from parsers.elexicon import parse_elexicon
        return parse_elexicon(pdf_path, filename)
    else:
        raise HTTPException(status_code=400, detail=f"Unknown invoice_type: {invoice_type!r}")


def _pdf_to_images(pdf_path: str) -> list[str]:
    """Convert all PDF pages to base64-encoded JPEGs. Returns [] if unavailable."""
    try:
        from pdf2image import convert_from_path  # type: ignore[import]
        images = convert_from_path(pdf_path, dpi=120)
        result: list[str] = []
        for img in images:
            buf = BytesIO()
            img.save(buf, format="JPEG", quality=82)
            result.append(base64.standard_b64encode(buf.getvalue()).decode())
        return result
    except Exception:
        return []


def _clean_row(row: dict[str, Any], strip_extra: set[str] | None = None) -> dict[str, Any]:
    """Strip auto-generated fields (and any extras) before DB write."""
    exclude = _AUTO_FIELDS | (strip_extra or set())
    return {k: v for k, v in row.items() if k not in exclude}



# ─────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    return {"status": "ok"}


# ── Request bodies ─────────────────────────────────────────────

class ParseRequest(BaseModel):
    invoice_type: str
    storage_path: str  # path in the 'invoices' bucket (uploaded by frontend before calling /parse)


class SaveRequest(BaseModel):
    invoice_type: str
    rows: list[dict[str, Any]]
    storage_path: Optional[str] = None  # already-uploaded PDF path in 'invoices' bucket


# ── Parse ─────────────────────────────────────────────────────

@app.post("/parse")
async def parse(body: ParseRequest):
    """
    Parse a PDF invoice. The PDF must already be uploaded to Supabase Storage.
    Returns extracted rows, validation warnings, and base64 page images.

    JSON body:
      invoice_type  — cambridge | pickering_cng | walgreen | pickering_elexicon
      storage_path  — path in the 'invoices' bucket (e.g. "temp/1234567890_invoice.pdf")
    """
    if body.invoice_type not in _TABLE_MAP:
        raise HTTPException(status_code=400, detail=f"Unknown invoice_type: {body.invoice_type!r}")

    sb = _get_supabase()
    try:
        content: bytes = sb.storage.from_(_STORAGE_BUCKET).download(body.storage_path)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Failed to download PDF from storage: {exc}") from exc

    filename = body.storage_path.split("/")[-1]

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp.write(content)
        tmp_path = tmp.name

    try:
        rows_pydantic, parse_warnings = _dispatch_parse(body.invoice_type, tmp_path, filename)
        row_dicts = [r.model_dump(mode="json") for r in rows_pydantic]
        page_images = _pdf_to_images(tmp_path)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    from validation import validate_rows
    val_warnings = validate_rows(body.invoice_type, row_dicts)
    all_warnings = [w.model_dump() for w in (parse_warnings + val_warnings)]

    return {
        "invoice_type": body.invoice_type,
        "rows": row_dicts,
        "warnings": all_warnings,
        "pdf_page_images": page_images,
        "storage_path": body.storage_path,
    }


# ── Parse (base64) ────────────────────────────────────────────

@app.post("/parse-b64")
async def parse_b64(request: Request):
    """
    Parse a PDF invoice sent as base64-encoded JSON.
    Used by the Supabase Edge Function proxy which cannot produce
    multipart/form-data that python-multipart can parse.

    JSON body:
      invoice_type  — cambridge | pickering_cng | walgreen | pickering_elexicon
      pdf_base64    — base64-encoded PDF bytes
      filename      — (optional) original filename, default "invoice.pdf"
    """
    try:
        body = await request.json()
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Invalid JSON body: {exc}") from exc

    invoice_type: str = body.get("invoice_type", "")
    pdf_base64: str = body.get("pdf_base64", "")
    filename: str = body.get("filename", "invoice.pdf")

    if not invoice_type or not pdf_base64:
        raise HTTPException(status_code=400, detail="invoice_type and pdf_base64 are required")
    if invoice_type not in _TABLE_MAP:
        raise HTTPException(status_code=400, detail=f"Unknown invoice_type: {invoice_type!r}")

    try:
        pdf_bytes = base64.b64decode(pdf_base64)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Invalid base64 data: {exc}") from exc

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp.write(pdf_bytes)
        tmp_path = tmp.name

    try:
        rows_pydantic, parse_warnings = _dispatch_parse(invoice_type, tmp_path, filename)
        row_dicts = [r.model_dump(mode="json") for r in rows_pydantic]
        page_images = _pdf_to_images(tmp_path)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    from validation import validate_rows
    val_warnings = validate_rows(invoice_type, row_dicts)
    all_warnings = [w.model_dump() for w in (parse_warnings + val_warnings)]

    return {
        "invoice_type": invoice_type,
        "rows": row_dicts,
        "warnings": all_warnings,
        "pdf_page_images": page_images,
    }


# ── Save ──────────────────────────────────────────────────────

@app.post("/save")
async def save(body: SaveRequest):
    """
    Insert parsed rows into Supabase. The PDF is already in Storage from the /parse step.

    JSON body:
      invoice_type  — site identifier
      rows          — list of row dicts (same shape as /parse response rows)
      storage_path  — (optional) path in 'invoices' bucket; stamped on each row as source_pdf_path
    """
    table = _TABLE_MAP.get(body.invoice_type)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown invoice_type: {body.invoice_type!r}")

    sb = _get_supabase()

    # Stamp each row with source_pdf_path if we have a storage path
    clean_rows = []
    for row in body.rows:
        clean = _clean_row(row)
        if body.storage_path:
            clean["source_pdf_path"] = body.storage_path
        clean_rows.append(clean)

    try:
        response = sb.table(table).insert(clean_rows).execute()
        inserted = len(response.data) if response.data else len(clean_rows)
        return {"success": True, "inserted": inserted}
    except Exception as exc:
        err = str(exc)
        if "duplicate" in err.lower() or "23505" in err or "unique" in err.lower():
            raise HTTPException(
                status_code=409,
                detail=(
                    "Duplicate record: one or more billing periods already exist. "
                    "Delete the existing records first, or correct the date range."
                ),
            )
        raise HTTPException(status_code=500, detail=err) from exc


# ── Records ───────────────────────────────────────────────────

@app.get("/records/{site_id}")
async def get_records(
    site_id: str,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    limit: Optional[int] = None,
):
    """
    Return saved records for a site, oldest first (ascending by order column).

    Date filter params apply to start_date / end_date columns (not the sort column):
      start_date — records where start_date >= this value
      end_date   — records where end_date <= this value
      limit      — maximum number of records to return
    """
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()
    order_col = _ORDER_COL[site_id]

    query = sb.table(table).select("*").order(order_col, desc=False)
    if start_date:
        query = query.gte("start_date", start_date)
    if end_date:
        query = query.lte("end_date", end_date)
    if limit:
        query = query.limit(limit)

    try:
        response = query.execute()
        return response.data
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.put("/records/{site_id}/{record_id}")
async def update_record(site_id: str, record_id: str, body: dict[str, Any]):
    """Update a single record by ID."""
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()
    clean = _clean_row(body)

    try:
        response = sb.table(table).update(clean).eq("id", record_id).execute()
        if not response.data:
            raise HTTPException(status_code=404, detail="Record not found.")
        return response.data[0]
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.delete("/records/{site_id}/{record_id}")
async def delete_record(site_id: str, record_id: str):
    """Delete a single record by ID."""
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()
    try:
        sb.table(table).delete().eq("id", record_id).execute()
        return {"success": True}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


# ── Duplicate Check ────────────────────────────────────────────

@app.get("/check-duplicate/{site_id}")
async def check_duplicate(
    site_id: str,
    invoice_number: Optional[str] = None,
    end_date: Optional[str] = None,
    cost: Optional[float] = None,
    read_period: Optional[str] = None,
    total_charge: Optional[float] = None,
):
    """
    Check whether a record with the given invoice details already exists.

    Step 1 (exact): if invoice_number is provided, match on that field.
    Step 2 (fuzzy): if no invoice_number, try:
      - Enbridge sites: end_date + enbridge_invoice_cost_excl_hst within $0.01
      - Elexicon: read_period + total_charge within $0.01

    Returns:
      { "duplicate": "none" }
      { "duplicate": "exact", "existing": {...} }
      { "duplicate": "fuzzy", "existing": {...} }
    """
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()

    # ── Step 1: invoice number exact match ──────────────────────────
    if invoice_number:
        try:
            resp = (
                sb.table(table)
                .select("*")
                .eq("invoice_number", invoice_number)
                .limit(1)
                .execute()
            )
            if resp.data:
                return {"duplicate": "exact", "existing": resp.data[0]}
        except Exception:
            pass  # field may not exist for this site; fall through to fuzzy

    # ── Step 2: fuzzy match ─────────────────────────────────────────
    if site_id == "pickering_elexicon":
        # Match on read_period + total_charge within $0.01
        if read_period and total_charge is not None:
            try:
                resp = (
                    sb.table(table)
                    .select("*")
                    .eq("read_period", read_period)
                    .execute()
                )
                for rec in (resp.data or []):
                    db_charge = rec.get("total_charge")
                    if db_charge is not None and abs(float(db_charge) - total_charge) <= 0.01:
                        return {"duplicate": "fuzzy", "existing": rec}
            except Exception:
                pass
    else:
        # Enbridge sites: match on end_date + enbridge_invoice_cost_excl_hst within $0.01
        if end_date and cost is not None:
            try:
                resp = (
                    sb.table(table)
                    .select("*")
                    .eq("end_date", end_date)
                    .execute()
                )
                for rec in (resp.data or []):
                    db_cost = rec.get("enbridge_invoice_cost_excl_hst")
                    if db_cost is not None and abs(float(db_cost) - cost) <= 0.01:
                        return {"duplicate": "fuzzy", "existing": rec}
            except Exception:
                pass

    return {"duplicate": "none"}


# ── Sites ─────────────────────────────────────────────────────

@app.get("/sites/{site_id}")
async def get_site(site_id: str):
    """Return site metadata from the sites table."""
    sb = _get_supabase()
    try:
        response = sb.table("sites").select("*").eq("id", site_id).single().execute()
        return response.data
    except Exception as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@app.put("/sites/{site_id}")
async def update_site(site_id: str, body: dict[str, Any]):
    """Update site metadata (display_name, address, account_number, etc.)."""
    sb = _get_supabase()
    allowed = {"display_name", "address", "account_number", "bill_number", "rate_description", "sage_notes"}
    clean = {k: v for k, v in body.items() if k in allowed}

    try:
        response = sb.table("sites").update(clean).eq("id", site_id).execute()
        if not response.data:
            raise HTTPException(status_code=404, detail="Site not found.")
        return response.data[0]
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


# ── PDF signed URL ────────────────────────────────────────────

@app.get("/pdf/{site_id}/{record_id}")
async def get_pdf_url(site_id: str, record_id: str):
    """
    Return a short-lived signed URL for the invoice PDF stored in Supabase Storage.
    Expires in 1 hour.
    """
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()

    try:
        response = sb.table(table).select("source_pdf_path").eq("id", record_id).single().execute()
        pdf_path = (response.data or {}).get("source_pdf_path")
    except Exception as exc:
        raise HTTPException(status_code=404, detail=f"Record not found: {exc}") from exc

    if not pdf_path:
        raise HTTPException(status_code=404, detail="No PDF stored for this record.")

    try:
        signed = sb.storage.from_(_STORAGE_BUCKET).create_signed_url(pdf_path, 3600)
        url = signed.get("signedURL") or signed.get("signedUrl") or ""
        if not url:
            raise ValueError("Empty signed URL returned")
        return {"url": url}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Could not generate signed URL: {exc}") from exc


# ── Excel Export ──────────────────────────────────────────────

@app.get("/export/{site_id}")
async def export_excel(site_id: str):
    """Download all records as .xlsx in Melissa's exact tracker format."""
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()
    order_col = _ORDER_COL[site_id]

    try:
        response = sb.table(table).select("*").order(order_col, desc=False).execute()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    from export.excel import export_to_excel
    excel_bytes = export_to_excel(site_id, response.data or [])
    filename = f"{_SITE_NAMES.get(site_id, site_id)}_Invoice_Tracker.xlsx"

    return StreamingResponse(
        BytesIO(excel_bytes),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
