"""
MWS Invoice Parser — FastAPI application.

Routes (all mounted at root; Vite proxy strips /api prefix):
  POST /parse          — upload PDF, parse, validate, return rows + page images
  POST /save           — insert parsed rows into Supabase
  GET  /records/{site} — fetch saved records (supports start_date / end_date filters)
  GET  /export/{site}  — download .xlsx tracker in Melissa's exact format
"""

from __future__ import annotations

import base64
import os
import tempfile
from io import BytesIO
from typing import Any, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

load_dotenv()

app = FastAPI(
    title="MWS Invoice Parser API",
    description="Parses Enbridge CNG and Elexicon electricity PDF invoices for Miller Waste Systems.",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "https://mws-invoice-parser.vercel.app",
        "https://mws-invoice-parser-skormzys-projects.vercel.app",
    ],
    allow_origin_regex=r"https://mws-invoice-parser-.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────

_TABLE_MAP = {
    "cambridge": "cambridge_invoices",
    "pickering_cng": "pickering_cng_invoices",
    "walgreen": "walgreen_invoices",
    "pickering_elexicon": "pickering_elexicon_invoices",
}

_ORDER_COL = {
    "cambridge": "start_date",
    "pickering_cng": "start_date",
    "walgreen": "start_date",
    "pickering_elexicon": "bill_period",
}

_SITE_NAMES = {
    "cambridge": "Cambridge_CNG",
    "pickering_cng": "Pickering_CNG",
    "walgreen": "Walgreen_CNG",
    "pickering_elexicon": "Pickering_Elexicon",
}

# Fields auto-generated by Supabase — strip before insert
_AUTO_FIELDS = {"id", "created_at"}


# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────

def _get_supabase():
    url = os.environ.get("SUPABASE_URL", "")
    key = os.environ.get("SUPABASE_SERVICE_KEY", "")
    if not url or not key:
        raise HTTPException(
            status_code=503,
            detail=(
                "Supabase is not configured. "
                "Set SUPABASE_URL and SUPABASE_SERVICE_KEY environment variables."
            ),
        )
    from supabase import create_client  # type: ignore[import]
    return create_client(url, key)


def _dispatch_parse(
    invoice_type: str, pdf_path: str, filename: str
) -> tuple[list[Any], list[Any]]:
    if invoice_type == "cambridge":
        from parsers.cambridge import parse_cambridge
        return parse_cambridge(pdf_path, filename)
    elif invoice_type == "pickering_cng":
        from parsers.pickering_enbridge import parse_pickering_enbridge
        return parse_pickering_enbridge(pdf_path, filename)
    elif invoice_type == "walgreen":
        from parsers.walgreen import parse_walgreen
        return parse_walgreen(pdf_path, filename)
    elif invoice_type == "pickering_elexicon":
        from parsers.elexicon import parse_elexicon
        return parse_elexicon(pdf_path, filename)
    else:
        raise HTTPException(status_code=400, detail=f"Unknown invoice_type: {invoice_type!r}")


def _pdf_to_images(pdf_path: str) -> list[str]:
    """Convert all PDF pages to base64-encoded JPEG strings. Returns [] if unavailable."""
    try:
        from pdf2image import convert_from_path  # type: ignore[import]

        images = convert_from_path(pdf_path, dpi=120)
        result: list[str] = []
        for img in images:
            buf = BytesIO()
            img.save(buf, format="JPEG", quality=82)
            result.append(base64.standard_b64encode(buf.getvalue()).decode())
        return result
    except Exception:
        return []


def _clean_row(row: dict[str, Any]) -> dict[str, Any]:
    """Strip auto-generated fields before inserting into Supabase."""
    return {k: v for k, v in row.items() if k not in _AUTO_FIELDS}


# ─────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    return {"status": "ok"}


@app.post("/parse")
async def parse(
    invoice_type: str = Form(...),
    file: UploadFile = File(...),
):
    """
    Parse an invoice PDF and return extracted rows + PDF page images.

    Multipart form fields:
      invoice_type — one of: cambridge | pickering_cng | walgreen | pickering_elexicon
      file         — the PDF file
    """
    if invoice_type not in _TABLE_MAP:
        raise HTTPException(status_code=400, detail=f"Unknown invoice_type: {invoice_type!r}")

    content = await file.read()

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp.write(content)
        tmp_path = tmp.name

    try:
        rows_pydantic, parse_warnings = _dispatch_parse(
            invoice_type, tmp_path, file.filename or ""
        )
        row_dicts = [r.model_dump(mode="json") for r in rows_pydantic]
        page_images = _pdf_to_images(tmp_path)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    # Post-parse validation (range checks, HST, date order)
    from validation import validate_rows
    val_warnings = validate_rows(invoice_type, row_dicts)

    all_warnings = [w.model_dump() for w in (parse_warnings + val_warnings)]

    return {
        "invoice_type": invoice_type,
        "rows": row_dicts,
        "warnings": all_warnings,
        "pdf_page_images": page_images,
    }


class SaveRequest(BaseModel):
    invoice_type: str
    rows: list[dict[str, Any]]


@app.post("/save")
async def save(request: SaveRequest):
    """
    Insert parsed rows into the correct Supabase table.

    Body: { invoice_type: string, rows: [...] }
    """
    table = _TABLE_MAP.get(request.invoice_type)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown invoice_type: {request.invoice_type!r}")

    sb = _get_supabase()
    clean_rows = [_clean_row(row) for row in request.rows]

    try:
        response = sb.table(table).insert(clean_rows).execute()
        inserted = len(response.data) if response.data else len(clean_rows)
        return {"success": True, "inserted": inserted}
    except Exception as exc:
        err = str(exc)
        if "duplicate" in err.lower() or "23505" in err or "unique" in err.lower():
            raise HTTPException(
                status_code=409,
                detail=(
                    "Duplicate record: one or more billing periods already exist in the database. "
                    "Delete the existing records first, or deselect the duplicate rows."
                ),
            )
        raise HTTPException(status_code=500, detail=err) from exc


@app.get("/records/{site_id}")
async def get_records(
    site_id: str,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
):
    """
    Return all saved records for a site, newest first.

    Query params (optional):
      start_date — ISO date, inclusive lower bound on the date ordering column
      end_date   — ISO date, inclusive upper bound
    """
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()
    order_col = _ORDER_COL[site_id]

    query = sb.table(table).select("*").order(order_col, desc=True)
    if start_date:
        query = query.gte(order_col, start_date)
    if end_date:
        query = query.lte(order_col, end_date)

    try:
        response = query.execute()
        return response.data
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.get("/export/{site_id}")
async def export_excel(site_id: str):
    """
    Download all records as an .xlsx file matching Melissa's tracker format.
    """
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()
    order_col = _ORDER_COL[site_id]

    try:
        response = sb.table(table).select("*").order(order_col, desc=False).execute()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    from export.excel import export_to_excel

    excel_bytes = export_to_excel(site_id, response.data or [])
    filename = f"{_SITE_NAMES.get(site_id, site_id)}_Invoice_Tracker.xlsx"

    return StreamingResponse(
        BytesIO(excel_bytes),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
