"""
MWS Invoice Parser — FastAPI application.

Routes (all mounted at root; Vite proxy strips /api prefix):
  POST /parse                      — upload PDF, parse, validate, return rows + page images
  POST /save                       — insert rows into Supabase; upload PDF to Storage
  GET  /records/{site}             — fetch saved records (asc start_date; optional filters)
  PUT  /records/{site}/{id}        — update a single record
  DELETE /records/{site}/{id}      — delete a single record
  GET  /sites/{site}               — get site metadata
  PUT  /sites/{site}               — update site metadata
  GET  /pdf/{site}/{id}            — get signed PDF download URL
  GET  /export/{site}              — download .xlsx tracker in Melissa's exact format
"""

from __future__ import annotations

import base64
import json
import os
import tempfile
from io import BytesIO
from typing import Any, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

load_dotenv()

app = FastAPI(
    title="MWS Invoice Parser API",
    description="Parses Enbridge CNG and Elexicon electricity PDF invoices for Miller Waste Systems.",
    version="0.2.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "https://mws-invoice-parser.vercel.app",
        "https://mws-invoice-parser-skormzys-projects.vercel.app",
    ],
    allow_origin_regex=r"https://mws-invoice-parser-.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────

_TABLE_MAP = {
    "cambridge": "cambridge_invoices",
    "pickering_cng": "pickering_cng_invoices",
    "walgreen": "walgreen_invoices",
    "pickering_elexicon": "pickering_elexicon_invoices",
}

# Column used for ascending date sort per site
_ORDER_COL = {
    "cambridge": "start_date",
    "pickering_cng": "start_date",
    "walgreen": "start_date",
    "pickering_elexicon": "created_at",
}

_SITE_NAMES = {
    "cambridge": "Cambridge_CNG",
    "pickering_cng": "Pickering_CNG",
    "walgreen": "Walgreen_CNG",
    "pickering_elexicon": "Pickering_Elexicon",
}

# Fields auto-generated by Supabase — strip before insert/update
_AUTO_FIELDS = {"id", "created_at"}

_STORAGE_BUCKET = "invoices"


# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────

def _get_supabase():
    url = os.environ.get("SUPABASE_URL", "")
    key = os.environ.get("SUPABASE_SERVICE_KEY", "")
    if not url or not key:
        raise HTTPException(
            status_code=503,
            detail="Supabase is not configured. Set SUPABASE_URL and SUPABASE_SERVICE_KEY.",
        )
    from supabase import create_client  # type: ignore[import]
    return create_client(url, key)


def _dispatch_parse(invoice_type: str, pdf_path: str, filename: str) -> tuple[list[Any], list[Any]]:
    if invoice_type == "cambridge":
        from parsers.cambridge import parse_cambridge
        return parse_cambridge(pdf_path, filename)
    elif invoice_type == "pickering_cng":
        from parsers.pickering_enbridge import parse_pickering_enbridge
        return parse_pickering_enbridge(pdf_path, filename)
    elif invoice_type == "walgreen":
        from parsers.walgreen import parse_walgreen
        return parse_walgreen(pdf_path, filename)
    elif invoice_type == "pickering_elexicon":
        from parsers.elexicon import parse_elexicon
        return parse_elexicon(pdf_path, filename)
    else:
        raise HTTPException(status_code=400, detail=f"Unknown invoice_type: {invoice_type!r}")


def _pdf_to_images(pdf_path: str) -> list[str]:
    """Convert all PDF pages to base64-encoded JPEGs. Returns [] if unavailable."""
    try:
        from pdf2image import convert_from_path  # type: ignore[import]
        images = convert_from_path(pdf_path, dpi=120)
        result: list[str] = []
        for img in images:
            buf = BytesIO()
            img.save(buf, format="JPEG", quality=82)
            result.append(base64.standard_b64encode(buf.getvalue()).decode())
        return result
    except Exception:
        return []


def _clean_row(row: dict[str, Any], strip_extra: set[str] | None = None) -> dict[str, Any]:
    """Strip auto-generated fields (and any extras) before DB write."""
    exclude = _AUTO_FIELDS | (strip_extra or set())
    return {k: v for k, v in row.items() if k not in exclude}


def _upload_pdf(sb, site_id: str, filename: str, content: bytes, rows: list[dict]) -> str:
    """
    Upload the invoice PDF to Supabase Storage.
    Path: {site_id}/{YYYY-MM}_{filename}
    Returns the storage path string.
    """
    # Derive YYYY-MM from first row's start_date (or today as fallback)
    from datetime import date as _date
    month_prefix: str
    first = rows[0] if rows else {}
    raw_date = first.get("start_date") or first.get("billing_period")
    if raw_date and len(str(raw_date)) >= 7:
        month_prefix = str(raw_date)[:7]
    else:
        month_prefix = _date.today().strftime("%Y-%m")

    safe_name = filename.replace(" ", "_")
    path = f"{site_id}/{month_prefix}_{safe_name}"

    try:
        sb.storage.from_(_STORAGE_BUCKET).upload(
            path,
            content,
            {"content-type": "application/pdf", "upsert": "true"},
        )
    except Exception as exc:
        # Log but don't fail the save — PDF upload is best-effort
        print(f"[WARN] PDF upload failed: {exc}")
        return ""

    return path


# ─────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    return {"status": "ok"}


# ── Parse ─────────────────────────────────────────────────────

@app.post("/parse")
async def parse(
    invoice_type: str = Form(...),
    file: UploadFile = File(...),
):
    """
    Parse a PDF invoice. Returns extracted rows, validation warnings, and base64 page images.

    Multipart fields:
      invoice_type — cambridge | pickering_cng | walgreen | pickering_elexicon
      file         — the PDF
    """
    if invoice_type not in _TABLE_MAP:
        raise HTTPException(status_code=400, detail=f"Unknown invoice_type: {invoice_type!r}")

    content = await file.read()

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp.write(content)
        tmp_path = tmp.name

    try:
        rows_pydantic, parse_warnings = _dispatch_parse(invoice_type, tmp_path, file.filename or "")
        row_dicts = [r.model_dump(mode="json") for r in rows_pydantic]
        page_images = _pdf_to_images(tmp_path)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    from validation import validate_rows
    val_warnings = validate_rows(invoice_type, row_dicts)
    all_warnings = [w.model_dump() for w in (parse_warnings + val_warnings)]

    return {
        "invoice_type": invoice_type,
        "rows": row_dicts,
        "warnings": all_warnings,
        "pdf_page_images": page_images,
    }


# ── Save ──────────────────────────────────────────────────────

@app.post("/save")
async def save(
    invoice_type: str = Form(...),
    rows: str = Form(...),           # JSON-encoded list of row dicts
    file: Optional[UploadFile] = File(None),
):
    """
    Insert parsed rows into Supabase and (optionally) upload the original PDF to Storage.

    Multipart fields:
      invoice_type — site identifier
      rows         — JSON string of row array (same shape as /parse response rows)
      file         — (optional) the original PDF for storage
    """
    table = _TABLE_MAP.get(invoice_type)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown invoice_type: {invoice_type!r}")

    try:
        rows_data: list[dict[str, Any]] = json.loads(rows)
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=400, detail=f"Invalid rows JSON: {exc}") from exc

    sb = _get_supabase()

    # Upload PDF to Storage and record path
    pdf_path_stored = ""
    if file is not None:
        pdf_content = await file.read()
        if pdf_content:
            pdf_path_stored = _upload_pdf(sb, invoice_type, file.filename or "invoice.pdf", pdf_content, rows_data)

    # Stamp each row with source_pdf_path
    clean_rows = []
    for row in rows_data:
        clean = _clean_row(row)
        if pdf_path_stored:
            clean["source_pdf_path"] = pdf_path_stored
        clean_rows.append(clean)

    try:
        response = sb.table(table).insert(clean_rows).execute()
        inserted = len(response.data) if response.data else len(clean_rows)
        return {"success": True, "inserted": inserted}
    except Exception as exc:
        err = str(exc)
        if "duplicate" in err.lower() or "23505" in err or "unique" in err.lower():
            raise HTTPException(
                status_code=409,
                detail=(
                    "Duplicate record: one or more billing periods already exist. "
                    "Delete the existing records first, or correct the date range."
                ),
            )
        raise HTTPException(status_code=500, detail=err) from exc


# ── Records ───────────────────────────────────────────────────

@app.get("/records/{site_id}")
async def get_records(
    site_id: str,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    limit: Optional[int] = None,
):
    """
    Return saved records for a site, oldest first (ascending).

    Query params (all optional):
      start_date — ISO date lower bound on the ordering column
      end_date   — ISO date upper bound
      limit      — maximum number of records to return
    """
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()
    order_col = _ORDER_COL[site_id]

    query = sb.table(table).select("*").order(order_col, desc=False)
    if start_date:
        query = query.gte(order_col, start_date)
    if end_date:
        query = query.lte(order_col, end_date)
    if limit:
        query = query.limit(limit)

    try:
        response = query.execute()
        return response.data
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.put("/records/{site_id}/{record_id}")
async def update_record(site_id: str, record_id: str, body: dict[str, Any]):
    """Update a single record by ID."""
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()
    clean = _clean_row(body)

    try:
        response = sb.table(table).update(clean).eq("id", record_id).execute()
        if not response.data:
            raise HTTPException(status_code=404, detail="Record not found.")
        return response.data[0]
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.delete("/records/{site_id}/{record_id}")
async def delete_record(site_id: str, record_id: str):
    """Delete a single record by ID."""
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()
    try:
        sb.table(table).delete().eq("id", record_id).execute()
        return {"success": True}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


# ── Sites ─────────────────────────────────────────────────────

@app.get("/sites/{site_id}")
async def get_site(site_id: str):
    """Return site metadata from the sites table."""
    sb = _get_supabase()
    try:
        response = sb.table("sites").select("*").eq("id", site_id).single().execute()
        return response.data
    except Exception as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@app.put("/sites/{site_id}")
async def update_site(site_id: str, body: dict[str, Any]):
    """Update site metadata (display_name, address, account_number, etc.)."""
    sb = _get_supabase()
    allowed = {"display_name", "address", "account_number", "bill_number", "rate_description", "sage_notes"}
    clean = {k: v for k, v in body.items() if k in allowed}

    try:
        response = sb.table("sites").update(clean).eq("id", site_id).execute()
        if not response.data:
            raise HTTPException(status_code=404, detail="Site not found.")
        return response.data[0]
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


# ── PDF signed URL ────────────────────────────────────────────

@app.get("/pdf/{site_id}/{record_id}")
async def get_pdf_url(site_id: str, record_id: str):
    """
    Return a short-lived signed URL for the invoice PDF stored in Supabase Storage.
    Expires in 1 hour.
    """
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()

    # Fetch the record to get source_pdf_path
    try:
        response = sb.table(table).select("source_pdf_path").eq("id", record_id).single().execute()
        pdf_path = (response.data or {}).get("source_pdf_path")
    except Exception as exc:
        raise HTTPException(status_code=404, detail=f"Record not found: {exc}") from exc

    if not pdf_path:
        raise HTTPException(status_code=404, detail="No PDF stored for this record.")

    try:
        signed = sb.storage.from_(_STORAGE_BUCKET).create_signed_url(pdf_path, 3600)
        url = signed.get("signedURL") or signed.get("signedUrl") or ""
        if not url:
            raise ValueError("Empty signed URL returned")
        return {"url": url}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Could not generate signed URL: {exc}") from exc


# ── Excel Export ──────────────────────────────────────────────

@app.get("/export/{site_id}")
async def export_excel(site_id: str):
    """Download all records as .xlsx in Melissa's exact tracker format."""
    table = _TABLE_MAP.get(site_id)
    if not table:
        raise HTTPException(status_code=400, detail=f"Unknown site_id: {site_id!r}")

    sb = _get_supabase()
    order_col = _ORDER_COL[site_id]

    try:
        response = sb.table(table).select("*").order(order_col, desc=False).execute()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    from export.excel import export_to_excel
    excel_bytes = export_to_excel(site_id, response.data or [])
    filename = f"{_SITE_NAMES.get(site_id, site_id)}_Invoice_Tracker.xlsx"

    return StreamingResponse(
        BytesIO(excel_bytes),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
